version: 2

sources:
  - name: so
    tables:
      - name: comment_events
        meta:
          dagster:
            asset_key: ["raw_comments"] # This metadata specifies the corresponding Dagster asset for this dbt source.